name: Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      CIBW_SKIP: "*27* pp* *35*"
      CIBW_BUILD: "cp310-*"
      CIBW_ENVIRONMENT: "DISABLE_NUMCODECS_AVX2=1"
      CIBW_ENVIRONMENT_MACOS: 'MACOSX_DEPLOYMENT_TARGET=10.9 DISABLE_NUMCODECS_AVX2=1 CFLAGS="$CFLAGS -Wno-implicit-function-declaration"'

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: actions/setup-python@v1
        name: Install Python
        with:
          python-version: "3.10"

      - uses: pypa/cibuildwheel@v2.5.0

      - name: Checksum
        uses: Huy-Ngo/gha-sha@v1.1.0
        with:
          glob: 'wheelhouse/*.whl'

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: 'Release numcodecs 0.9.1 for cp310'
          files: wheelhouse/*.whl
          tag_name: v0.9.1
